# Generated by Django 3.2.5 on 2021-11-22 11:00

from django.conf import settings
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Контент статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/%d', verbose_name='Изображение')),
                ('file', models.FileField(blank=True, upload_to=news.models.update_filename, verbose_name='Файл к новости')),
                ('slug', models.SlugField(null=True, verbose_name='Slug')),
                ('user_visible', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Статья для пользователя')),
            ],
            options={
                'verbose_name': 'Cтатья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
