# Generated by Django 3.2.5 on 2021-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='news/%Y/%m/%d', verbose_name='Файл к новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
