# Generated by Django 3.2.5 on 2021-09-30 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='user_visible',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Статья для пользователя'),
        ),
    ]
