# Generated by Django 3.2.5 on 2021-11-09 17:08

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to=news.models.update_filename, verbose_name='Файл к новости'),
        ),
    ]
