# Generated by Django 3.2.5 on 2021-10-01 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_news_user_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='user_visible',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Статья для пользователя'),
        ),
    ]
