# Generated by Django 3.2.5 on 2021-10-11 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя артиста')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_update_photo', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3, verbose_name='Обновить/добавить фото в карточках артиста на площадках?')),
                ('photo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание фото')),
                ('photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Прикрепить фото')),
                ('content_type', models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=9, verbose_name='Тип релиза')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
