# Generated by Django 3.2.5 on 2021-10-15 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя артиста')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_update_photo', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3, verbose_name='Необходимо ли обновить/добавить фото в карточках артиста на площадках?')),
                ('photo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание фото')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Прикрепить фото')),
                ('content_type', models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=9, verbose_name='Тип релиза')),
                ('num_songs', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], default=1, null=True, verbose_name='Количество песен для отправки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songer', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('song_title', models.CharField(max_length=100, verbose_name='Название песни')),
                ('album_title', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('feat', models.CharField(blank=True, max_length=100, null=True, verbose_name='feat.')),
                ('genre', models.CharField(choices=[('BLUES', 'BLUES'), ('CHILDREN`S', 'CHILDREN`S'), ('CHRISTIAN', 'CHRISTIAN'), ('CLASSICAL', 'CLASSICAL'), ('COUNTRY', 'COUNTRY'), ('EDUCATIONAL', 'EDUCATIONAL'), ('ELECTRONIC', 'ELECTRONIC'), ('FOLK', 'FOLK'), ('HIP-HOP/RAP', 'HIP-HOP/RAP'), ('HOLIDAY', 'HOLIDAY'), ('JAZZ', 'JAZZ'), ('LATIN MUSIC', 'LATIN MUSIC'), ('METAL', 'METAL'), ('NEW AGE', 'NEW AGE'), ('POP', 'POP'), ('ALTERNATIVE', 'ALTERNATIVE'), ('R&B', 'R&B'), ('ROCK', 'ROCK'), ('PUNK', 'PUNK'), ('WORLD MUSIC', 'WORLD MUSIC')], max_length=11, verbose_name='Жанр')),
                ('fio_songer', models.CharField(max_length=100, verbose_name='ФИО Исполнителя')),
                ('words_author', models.CharField(max_length=100, verbose_name='Автор слов')),
                ('music_author', models.CharField(max_length=100, verbose_name='Автор музыки')),
                ('owner_citizenship', models.CharField(max_length=50, verbose_name='Гражданство изначального владельца авторских прав (артиста)')),
                ('record_country', models.CharField(max_length=100, verbose_name='Страна записи')),
                ('timing', models.CharField(max_length=5, verbose_name='Хронометраж')),
                ('song_preview', models.CharField(max_length=15, verbose_name='Превью песни')),
                ('lexis', models.CharField(choices=[('NO', 'Отсутствует'), ('YES', 'Присутствует')], max_length=15, verbose_name='Ненормативная лексика в песне')),
                ('cover', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка (jpg 3000x3000)')),
                ('cover_psd', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка песни в слоях (PSD)')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Аудио (WAV)')),
                ('audio_link', models.URLField(blank=True, null=True, verbose_name='Аудио (WAV)')),
                ('clean_link', models.URLField(verbose_name='Clean version трека (WAV)')),
                ('song_text', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Текст песни')),
                ('release_year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('add_video', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
