# Generated by Django 3.2.5 on 2021-10-06 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import release.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('is_update_photo', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=3)),
                ('photo', models.ImageField(upload_to=release.models.user_directory_path)),
                ('content_type', models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом'), ('CLIP', 'Видеоклип')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
