# Generated by Django 3.2.5 on 2021-10-06 16:03

from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion
import release.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='photo_link',
            field=models.URLField(null=True, verbose_name='Ссылка на скачивание фото'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='content_type',
            field=models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом'), ('CLIP', 'Видеоклип')], max_length=9, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='is_update_photo',
            field=models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=3, verbose_name='Обновить/добавить фото в карточках артиста на площадках?'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя артиста'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='photo',
            field=models.ImageField(upload_to=release.models.user_directory_path, verbose_name='Прикрепить фото'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
