# Generated by Django 3.2.5 on 2021-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='lexis',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('NO', 'Отсутствует'), ('YES', 'Присутствует')], default='NONE', max_length=15, verbose_name='Ненормативная лексика в видео'),
        ),
    ]
