# Generated by Django 3.2.5 on 2021-10-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Прикрепить фото'),
        ),
    ]
