# Generated by Django 3.2.5 on 2021-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_alter_video_lexis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='album_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название релиза'),
        ),
    ]
