# Generated by Django 3.2.5 on 2021-10-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_rename_release_songers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='№'),
        ),
    ]
