# Generated by Django 3.2.5 on 2021-10-06 16:04

from django.db import migrations, models
import release.models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20211006_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=release.models.user_directory_path, verbose_name='Прикрепить фото'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='photo_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на скачивание фото'),
        ),
    ]
