# Generated by Django 3.2.5 on 2021-10-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_alter_maininfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songer', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('song_title', models.CharField(max_length=100, verbose_name='Название песни')),
                ('album_title', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('feat', models.CharField(blank=True, max_length=100, null=True, verbose_name='feat.')),
                ('genre', models.CharField(choices=[('BLUES', 'BLUES'), ('CHILDREN`S', 'CHILDREN`S'), ('CHRISTIAN', 'CHRISTIAN'), ('CLASSICAL', 'CLASSICAL'), ('COUNTRY', 'COUNTRY'), ('EDUCATIONAL', 'EDUCATIONAL'), ('ELECTRONIC', 'ELECTRONIC'), ('FOLK', 'FOLK'), ('HIP-HOP/RAP', 'HIP-HOP/RAP'), ('HOLIDAY', 'HOLIDAY'), ('JAZZ', 'JAZZ'), ('LATIN MUSIC', 'LATIN MUSIC'), ('METAL', 'METAL'), ('NEW AGE', 'NEW AGE'), ('POP', 'POP'), ('ALTERNATIVE', 'ALTERNATIVE'), ('R&B', 'R&B'), ('ROCK', 'ROCK'), ('PUNK', 'PUNK'), ('WORLD MUSIC', 'WORLD MUSIC')], max_length=11, verbose_name='Жанр')),
                ('fio_songer', models.CharField(max_length=100, verbose_name='ФИО Исполнителя')),
                ('words_author', models.CharField(max_length=100, verbose_name='Автор слов')),
                ('music_author', models.CharField(max_length=100, verbose_name='Автор музыки')),
                ('owner_citizenship', models.CharField(max_length=50, verbose_name='Гражданство изначального владельца авторских прав (артиста)')),
                ('record_country', models.CharField(max_length=100, verbose_name='Страна записи')),
                ('timing', models.CharField(max_length=5, verbose_name='Хронометраж')),
                ('song_preview', models.CharField(max_length=15, verbose_name='Превью песни')),
                ('lexis', models.CharField(choices=[('NO', 'Отсутствует'), ('YES', 'Присутствует')], max_length=15, verbose_name='Ненормативная лексика в песне')),
                ('cover', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка (jpg 3000x3000)')),
                ('cover_psd', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка песни в слоях (PSD)')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Аудио (WAV)')),
                ('audio_link', models.URLField(blank=True, null=True, verbose_name='Аудио (WAV)')),
                ('clean_link', models.URLField(verbose_name='Clean version трека (WAV)')),
                ('song_text', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Текст песни')),
                ('release_year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('add_video', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='is_update_photo',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3, verbose_name='Необходимо ли обновить/добавить фото в карточках артиста на площадках?'),
        ),
    ]
