# Generated by Django 3.2.5 on 2021-10-06 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('release', '0003_auto_20211006_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='content_type',
            field=models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=9, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
