# Generated by Django 3.2.5 on 2021-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_auto_20211006_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='is_update_photo',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3, verbose_name='Обновить/добавить фото в карточках артиста на площадках?'),
        ),
    ]
