# Generated by Django 3.2.5 on 2021-10-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_alter_audio_add_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка (jpg 3000x3000)'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='cover_psd',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка в слоях (PSD)'),
        ),
    ]
