# Generated by Django 3.2.5 on 2021-10-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0006_auto_20211018_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='cover_psd',
        ),
    ]
