# Generated by Django 3.2.5 on 2021-10-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_auto_20211018_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='song_text',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Текст песни'),
        ),
    ]
