# Generated by Django 3.2.5 on 2021-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0011_auto_20211019_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='add_video',
            field=models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], default='NO', max_length=3, verbose_name='Добавить видеоклип'),
        ),
    ]
