# Generated by Django 3.2.5 on 2021-10-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0012_audio_add_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='add_video',
        ),
    ]
