# Generated by Django 3.2.5 on 2021-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0015_alter_audio_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('BLUES', 'BLUES'), ('CHILDREN`S', 'CHILDREN`S'), ('CHRISTIAN', 'CHRISTIAN'), ('CLASSICAL', 'CLASSICAL'), ('COUNTRY', 'COUNTRY'), ('EDUCATIONAL', 'EDUCATIONAL'), ('ELECTRONIC', 'ELECTRONIC'), ('FOLK', 'FOLK'), ('HIP-HOP/RAP', 'HIP-HOP/RAP'), ('HOLIDAY', 'HOLIDAY'), ('JAZZ', 'JAZZ'), ('LATIN MUSIC', 'LATIN MUSIC'), ('METAL', 'METAL'), ('NEW AGE', 'NEW AGE'), ('POP', 'POP'), ('ALTERNATIVE', 'ALTERNATIVE'), ('R&B', 'R&B'), ('ROCK', 'ROCK'), ('PUNK', 'PUNK'), ('WORLD MUSIC', 'WORLD MUSIC')], max_length=11, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='lexis',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('NO', 'Отсутствует'), ('YES', 'Присутствует')], default='NONE', max_length=15, verbose_name='Ненормативная лексика в песне'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='is_update_photo',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('NO', 'Нет'), ('YES', 'Да')], default='NONE', max_length=4, verbose_name='Необходимо ли обновить/добавить фото в карточках артиста на площадках?'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lexis',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('NO', 'Отсутствует'), ('YES', 'Присутствует')], default='NONE', max_length=15, verbose_name='Ненормативная лексика в песне'),
        ),
    ]
