# Generated by Django 3.2.5 on 2021-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0018_alter_maininfo_is_update_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('BLUES', 'BLUES'), ('CHILDREN`S', 'CHILDREN`S'), ('CHRISTIAN', 'CHRISTIAN'), ('CLASSICAL', 'CLASSICAL'), ('COUNTRY', 'COUNTRY'), ('EDUCATIONAL', 'EDUCATIONAL'), ('ELECTRONIC', 'ELECTRONIC'), ('FOLK', 'FOLK'), ('HIP-HOP/RAP', 'HIP-HOP/RAP'), ('HOLIDAY', 'HOLIDAY'), ('JAZZ', 'JAZZ'), ('LATIN MUSIC', 'LATIN MUSIC'), ('METAL', 'METAL'), ('NEW AGE', 'NEW AGE'), ('POP', 'POP'), ('ALTERNATIVE', 'ALTERNATIVE'), ('R&B', 'R&B'), ('ROCK', 'ROCK'), ('PUNK', 'PUNK'), ('WORLD MUSIC', 'WORLD MUSIC')], default='NONE', max_length=11, verbose_name='Жанр'),
        ),
    ]
