# Generated by Django 3.2.5 on 2021-11-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0020_auto_20211104_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аудио'),
        ),
    ]
