# Generated by Django 3.2.5 on 2021-11-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0021_alter_audio_audio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='instrumental',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Instrumental (минус)'),
        ),
    ]
