# Generated by Django 3.2.5 on 2021-11-05 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0022_audio_instrumental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='timing',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='[0-9]{2}:[0-9]{2}')], verbose_name='Хронометраж'),
        ),
    ]
