# Generated by Django 3.2.5 on 2021-11-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0024_alter_maininfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Обложка (jpg 3000x3000)'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='cover_psd',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Обложка в слоях (PSD)'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Прикрепить фото'),
        ),
    ]
