# Generated by Django 3.2.5 on 2021-11-09 16:43

from django.db import migrations, models
import release.models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0025_auto_20211109_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=release.models.update_filename, verbose_name='Обложка (jpg 3000x3000)'),
        ),
    ]
