# Generated by Django 3.2.5 on 2021-10-21 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Радио')),
                ('pressa', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Пресса')),
                ('social_crops', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Посевы в соцсетях')),
                ('tv', models.CharField(blank=True, max_length=1024, null=True, verbose_name='TV')),
                ('info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Информация по клипу')),
                ('other', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Другая информация по продвижению релиза')),
                ('project_plan', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Планы по развитию проекта')),
                ('release_plan', models.CharField(blank=True, max_length=1024, null=True, verbose_name='План релизов на ближайшие полгода')),
                ('press_release', models.TextField(verbose_name='Пресс-релиз')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positioning', models.CharField(max_length=500, verbose_name='Позиционирование')),
                ('where_from', models.CharField(max_length=500, verbose_name='Страна / город')),
                ('affiliation', models.CharField(max_length=500, verbose_name='Принадлежность к музыкальному / творческому сообществу')),
                ('awards', models.CharField(max_length=1024, verbose_name='Основные музыкальные награды и достижения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Качественные фотографии, которые будут отправлены редакторам площадок')),
                ('photo_link', models.URLField(blank=True, null=True, verbose_name='Качественные фотографии, которые будут отправлены редакторам площадок')),
                ('inspiration', models.CharField(max_length=2048, verbose_name='Источник вдохновения (Артисты, альбомы, фильмы, страны и т.д.)')),
                ('concept', models.CharField(max_length=2048, verbose_name='Концепция записи // Идея, главная задумка')),
                ('guest_artists', models.CharField(max_length=1024, verbose_name='Приглашенные артисты и продюсеры с примерами песен, в записи которых они участвовали')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainInfoMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songers', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('release_title', models.CharField(max_length=100, verbose_name='Название релиза')),
                ('release_type', models.CharField(choices=[('CLIP', 'Видеоклип'), ('SINGLE', 'Сингл'), ('ALBUM', 'Альбом / ЕР'), ('MAXI_SINGLE', 'Максисингл')], max_length=20, verbose_name='Тип релиза')),
                ('genre', models.CharField(choices=[('BLUES', 'BLUES'), ('CHILDREN`S', 'CHILDREN`S'), ('CHRISTIAN', 'CHRISTIAN'), ('CLASSICAL', 'CLASSICAL'), ('COUNTRY', 'COUNTRY'), ('EDUCATIONAL', 'EDUCATIONAL'), ('ELECTRONIC', 'ELECTRONIC'), ('FOLK', 'FOLK'), ('HIP-HOP/RAP', 'HIP-HOP/RAP'), ('HOLIDAY', 'HOLIDAY'), ('JAZZ', 'JAZZ'), ('LATIN MUSIC', 'LATIN MUSIC'), ('METAL', 'METAL'), ('NEW AGE', 'NEW AGE'), ('POP', 'POP'), ('ALTERNATIVE', 'ALTERNATIVE'), ('R&B', 'R&B'), ('ROCK', 'ROCK'), ('PUNK', 'PUNK'), ('WORLD MUSIC', 'WORLD MUSIC')], max_length=20, verbose_name='Жанр')),
                ('vk', models.CharField(max_length=100, verbose_name='VK')),
                ('inst', models.CharField(max_length=50, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True, verbose_name='TikTok')),
                ('other', models.CharField(blank=True, max_length=500, null=True, verbose_name='Другие социальные сети')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
