# Generated by Django 3.2.5 on 2021-11-22 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfoMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songers', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('release_title', models.CharField(max_length=100, verbose_name='Название релиза')),
                ('vk', models.CharField(max_length=100, verbose_name='VK')),
                ('inst', models.CharField(max_length=50, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube')),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True, verbose_name='TikTok')),
                ('other', models.CharField(blank=True, max_length=500, null=True, verbose_name='Другие социальные сети')),
                ('focus_track', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фокус-трек (если у вас альбом или EP)')),
                ('photo_link', models.URLField(verbose_name='Cсылка на качественные фотографии, которые будут отправлены редакторам площадок')),
                ('press_release', models.TextField(verbose_name='Пресс-релиз об артисте (основные музыкальные награды и достижения), пару слов о предстоящем релизе (идея, история создания)')),
                ('pr', models.TextField(verbose_name='PR проработка релиза: информация о радиостанциях, печатных изданиях, онлайн СМИ с вашей стороны')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
