# Generated by Django 3.2.5 on 2021-10-24 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0002_auto_20211024_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('MAXI_SINGLE', 'Максисингл'), ('ALBUM', 'Альбом / ЕР'), ('SINGLE', 'Сингл'), ('CLIP', 'Видеоклип')], max_length=20, verbose_name='Тип релиза'),
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_release', models.TextField(verbose_name='Пресс-релиз')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
