# Generated by Django 3.2.5 on 2021-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_alter_maininfomarketing_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('ALBUM', 'Альбом / ЕР'), ('SINGLE', 'Сингл'), ('MAXI_SINGLE', 'Максисингл'), ('CLIP', 'Видеоклип')], max_length=20, verbose_name='Тип релиза'),
        ),
    ]
