# Generated by Django 3.2.5 on 2021-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alter_maininfomarketing_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='genre',
            field=models.CharField(choices=[('NONE', 'Не выбрано'), ('BLUES', 'BLUES'), ('CHILDREN`S', 'CHILDREN`S'), ('CHRISTIAN', 'CHRISTIAN'), ('CLASSICAL', 'CLASSICAL'), ('COUNTRY', 'COUNTRY'), ('EDUCATIONAL', 'EDUCATIONAL'), ('ELECTRONIC', 'ELECTRONIC'), ('FOLK', 'FOLK'), ('HIP-HOP/RAP', 'HIP-HOP/RAP'), ('HOLIDAY', 'HOLIDAY'), ('JAZZ', 'JAZZ'), ('LATIN MUSIC', 'LATIN MUSIC'), ('METAL', 'METAL'), ('NEW AGE', 'NEW AGE'), ('POP', 'POP'), ('ALTERNATIVE', 'ALTERNATIVE'), ('R&B', 'R&B'), ('ROCK', 'ROCK'), ('PUNK', 'PUNK'), ('WORLD MUSIC', 'WORLD MUSIC')], default='NONE', max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('ALBUM', 'Альбом / ЕР'), ('MAXI_SINGLE', 'Максисингл'), ('SINGLE', 'Сингл'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=20, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='press_release',
            field=models.TextField(max_length=4096, verbose_name='Пресс-релиз'),
        ),
    ]
