# Generated by Django 3.2.5 on 2021-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_auto_20211027_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('SINGLE', 'Сингл'), ('MAXI_SINGLE', 'Максисингл'), ('ALBUM', 'Альбом / ЕР'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=20, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='press_release',
            field=models.TextField(verbose_name='Пресс-релиз'),
        ),
    ]
