# Generated by Django 3.2.5 on 2021-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_auto_20211027_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('MAXI_SINGLE', 'Максисингл'), ('CLIP', 'Видеоклип'), ('ALBUM', 'Альбом / ЕР'), ('SINGLE', 'Сингл')], default='SINGLE', max_length=20, verbose_name='Тип релиза'),
        ),
    ]
