# Generated by Django 3.2.5 on 2021-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_auto_20211031_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('CLIP', 'Видеоклип'), ('MAXI_SINGLE', 'Максисингл'), ('ALBUM', 'Альбом / ЕР'), ('SINGLE', 'Сингл')], default='SINGLE', max_length=20, verbose_name='Тип релиза'),
        ),
    ]
