# Generated by Django 3.2.5 on 2021-11-09 17:08

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0034_alter_maininfomarketing_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfomarketing',
            name='release_type',
            field=models.CharField(choices=[('MAXI_SINGLE', 'Максисингл'), ('ALBUM', 'Альбом / ЕР'), ('SINGLE', 'Сингл'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=20, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=marketing.models.update_filename, verbose_name='Качественные фотографии, которые будут отправлены редакторам площадок'),
        ),
    ]
