# Generated by Django 3.2.5 on 2021-10-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfoDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_are', models.CharField(choices=[('IPRF', 'ИП РФ'), ('IPIN', 'ИП Иностранный'), ('SAM', 'Самозанятый'), ('OOO', 'ООО')], max_length=20, verbose_name='Вы являетесь')),
                ('partners_value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=1, null=True, verbose_name='Количество участников')),
                ('artist_name', models.CharField(max_length=100, verbose_name='Имя артиста')),
                ('artist_fio', models.CharField(max_length=100, verbose_name='ФИО Артиста')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Телефон для связи')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('socials', models.CharField(max_length=500, verbose_name='Социальные сети')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
