# Generated by Django 3.2.5 on 2021-10-20 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_maininfodocs_you_are'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgInfoIpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('id_number', models.IntegerField(verbose_name='Идентификационный номер')),
                ('bank', models.CharField(max_length=50, verbose_name='Банк')),
                ('r_s', models.IntegerField(verbose_name='Расчетный счет')),
                ('bik', models.IntegerField(verbose_name='БИК')),
                ('inn_bank', models.IntegerField(verbose_name='ИНН Банка')),
                ('k_s', models.IntegerField(verbose_name='Корреспондентский счет')),
            ],
        ),
        migrations.CreateModel(
            name='OrgInfoOoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('fio_gen_dir', models.CharField(max_length=100, verbose_name='ФИО Генерального директора')),
                ('ogrn', models.IntegerField(verbose_name='ОГРН')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('kpp', models.IntegerField(verbose_name='КПП')),
                ('yur_address', models.CharField(max_length=2024, verbose_name='Юридический адрес')),
                ('fact_address', models.CharField(max_length=2024, verbose_name='Фактический адрес')),
                ('bank', models.CharField(max_length=50, verbose_name='Банк')),
                ('r_s', models.IntegerField(verbose_name='Расчетный счет')),
                ('bik', models.IntegerField(verbose_name='БИК')),
                ('inn_bank', models.IntegerField(verbose_name='ИНН Банка')),
                ('k_s', models.IntegerField(verbose_name='Корреспондентский счет')),
            ],
        ),
        migrations.CreateModel(
            name='OrgInfoSam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('series_num', models.IntegerField(verbose_name='Серия и номер паспорта')),
                ('who_issued', models.CharField(max_length=500, verbose_name='Кем выдан')),
                ('when_issued', models.DateField(verbose_name='Дата выдачи')),
                ('code_pod', models.IntegerField(verbose_name='Код подразделения')),
                ('birth_place', models.CharField(max_length=2024, verbose_name='Место рождения')),
                ('reg', models.CharField(max_length=2024, verbose_name='Регистрация')),
                ('bank', models.CharField(max_length=50, verbose_name='Банк')),
                ('r_s', models.IntegerField(verbose_name='Расчетный счет')),
                ('bik', models.IntegerField(verbose_name='БИК')),
                ('inn_bank', models.IntegerField(verbose_name='ИНН Банка')),
                ('k_s', models.IntegerField(verbose_name='Корреспондентский счет')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('snils', models.IntegerField(verbose_name='СНИЛС')),
                ('skan_passport', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Скан паспорта')),
            ],
        ),
        migrations.CreateModel(
            name='OrgInfoIprf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('ogrnip', models.IntegerField(verbose_name='ОГРНИП')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('bank', models.CharField(max_length=50, verbose_name='Банк')),
                ('r_s', models.IntegerField(verbose_name='Расчетный счет')),
                ('bik', models.IntegerField(verbose_name='БИК')),
                ('inn_bank', models.IntegerField(verbose_name='ИНН Банка')),
                ('k_s', models.IntegerField(verbose_name='Корреспондентский счет')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
