# Generated by Django 3.2.5 on 2021-10-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20211020_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfodocs',
            name='partners_value',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='orginfoipin',
            name='bik',
            field=models.CharField(max_length=100, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='orginfoipin',
            name='id_number',
            field=models.CharField(max_length=100, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='orginfoipin',
            name='inn_bank',
            field=models.CharField(max_length=100, verbose_name='ИНН Банка'),
        ),
        migrations.AlterField(
            model_name='orginfoipin',
            name='k_s',
            field=models.CharField(max_length=100, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='orginfoipin',
            name='r_s',
            field=models.CharField(max_length=100, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='bik',
            field=models.CharField(max_length=100, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='inn',
            field=models.CharField(max_length=100, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='inn_bank',
            field=models.CharField(max_length=100, verbose_name='ИНН Банка'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='k_s',
            field=models.CharField(max_length=100, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='ogrnip',
            field=models.CharField(max_length=100, verbose_name='ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='r_s',
            field=models.CharField(max_length=100, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='bik',
            field=models.CharField(max_length=100, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='inn',
            field=models.CharField(max_length=100, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='inn_bank',
            field=models.CharField(max_length=100, verbose_name='ИНН Банка'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='k_s',
            field=models.CharField(max_length=100, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='kpp',
            field=models.CharField(max_length=100, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='ogrn',
            field=models.CharField(max_length=100, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='r_s',
            field=models.CharField(max_length=100, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='bik',
            field=models.CharField(max_length=100, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='code_pod',
            field=models.CharField(max_length=100, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='inn',
            field=models.CharField(max_length=100, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='inn_bank',
            field=models.CharField(max_length=100, verbose_name='ИНН Банка'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='k_s',
            field=models.CharField(max_length=100, verbose_name='Корреспондентский счет'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='r_s',
            field=models.CharField(max_length=100, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='series_num',
            field=models.CharField(max_length=100, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='snils',
            field=models.CharField(max_length=100, verbose_name='СНИЛС'),
        ),
    ]
