# Generated by Django 3.2.5 on 2021-10-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_auto_20211020_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfodocs',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка (jpg 3000x3000)'),
        ),
        migrations.AddField(
            model_name='maininfodocs',
            name='num_songs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1, null=True, verbose_name='Количество песен для отправки'),
        ),
        migrations.CreateModel(
            name='VideoDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songers', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('video_title', models.CharField(max_length=100, verbose_name='Название видео')),
                ('words_author', models.CharField(max_length=100, verbose_name='Автор слов')),
                ('music_author', models.CharField(max_length=100, verbose_name='Автор музыки')),
                ('phon_maker', models.CharField(max_length=100, verbose_name='Изготовитель фонограммы')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('timing', models.CharField(max_length=5, verbose_name='Хронометраж')),
                ('release_year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('production_country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songers', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('song_title', models.CharField(max_length=100, verbose_name='Название песни')),
                ('album_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название альбома')),
                ('words_author', models.CharField(max_length=100, verbose_name='Автор слов')),
                ('music_author', models.CharField(max_length=100, verbose_name='Автор музыки')),
                ('phon_maker', models.CharField(max_length=100, verbose_name='Изготовитель фонограммы')),
                ('timing', models.CharField(max_length=5, verbose_name='Хронометраж')),
                ('release_year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
