# Generated by Django 3.2.5 on 2021-10-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_auto_20211020_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_author', models.CharField(choices=[('LIC', 'Лицензия'), ('ALI', 'Отчуждение')], max_length=15, verbose_name='Автор музыки передает вам права по лицензии или происходит отчуждение прав?')),
                ('words_author', models.CharField(choices=[('LIC', 'Лицензия'), ('ALI', 'Отчуждение')], max_length=15, verbose_name='Автор текста передает вам права по лицензии или происходит отчуждение прав?')),
                ('phon_maker', models.CharField(choices=[('LIC', 'Лицензия'), ('ALI', 'Отчуждение')], max_length=15, verbose_name='Изготовитель фонограммы передает вам права по лицензии или происходит отчуждение прав?')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
