# Generated by Django 3.2.5 on 2021-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='music_author',
            field=models.CharField(choices=[('LIC', 'Лицензия'), ('ALI', 'Отчуждение')], default='LIC', max_length=15, verbose_name='Автор музыки передает вам права по лицензии или происходит отчуждение прав?'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='phon_maker',
            field=models.CharField(choices=[('LIC', 'Лицензия'), ('ALI', 'Отчуждение')], default='LIC', max_length=15, verbose_name='Изготовитель фонограммы передает вам права по лицензии или происходит отчуждение прав?'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='words_author',
            field=models.CharField(choices=[('LIC', 'Лицензия'), ('ALI', 'Отчуждение')], default='LIC', max_length=15, verbose_name='Автор текста передает вам права по лицензии или происходит отчуждение прав?'),
        ),
    ]
