# Generated by Django 3.2.5 on 2021-10-21 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0009_musiccitizen_musicforeign_wordscitizen_wordsforeign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_name', models.CharField(max_length=100, verbose_name='Творческий псевдоним')),
                ('songs', models.CharField(max_length=500, verbose_name='Песня, в которой этот исполнитель учавствует')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('series_num', models.CharField(max_length=100, verbose_name='Серия и номер паспорта')),
                ('id_number', models.CharField(max_length=100, verbose_name='Идентификационный номер')),
                ('who_issued', models.CharField(max_length=500, verbose_name='Кем выдан')),
                ('when_issued', models.DateField(verbose_name='Дата выдачи')),
                ('code_pod', models.CharField(max_length=100, verbose_name='Код подразделения')),
                ('birth_place', models.CharField(max_length=2024, verbose_name='Место рождения')),
                ('reg', models.CharField(max_length=2024, verbose_name='Регистрация')),
                ('fin_conditions', models.CharField(max_length=2024, verbose_name='Финансовые условия с автором музыки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
