# Generated by Django 3.2.5 on 2021-10-21 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0010_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonMakerForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('passport', models.CharField(max_length=2024, verbose_name='Паспортные данные')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Электронная почта автора')),
                ('fin_conditions', models.CharField(max_length=2024, verbose_name='Финансовые условия с автором музыки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhonMakerCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('series_num', models.CharField(max_length=100, verbose_name='Серия и номер паспорта')),
                ('who_issued', models.CharField(max_length=500, verbose_name='Кем выдан')),
                ('when_issued', models.DateField(verbose_name='Дата выдачи')),
                ('code_pod', models.CharField(max_length=100, verbose_name='Код подразделения')),
                ('birth_place', models.CharField(max_length=2024, verbose_name='Место рождения')),
                ('reg', models.CharField(max_length=2024, verbose_name='Регистрация')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Электронная почта автора')),
                ('fin_conditions', models.CharField(max_length=2024, verbose_name='Финансовые условия с автором музыки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
