# Generated by Django 3.2.5 on 2021-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_phonmakercitizen_phonmakerforeign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfodocs',
            name='socials',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Социальные сети'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='skan_passport',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='snils',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='others',
            name='birth_place',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='others',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='others',
            name='citizen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='others',
            name='code_pod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='others',
            name='creative_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Творческий псевдоним'),
        ),
        migrations.AlterField(
            model_name='others',
            name='fin_conditions',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Финансовые условия с автором музыки'),
        ),
        migrations.AlterField(
            model_name='others',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='others',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='others',
            name='reg',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Регистрация'),
        ),
        migrations.AlterField(
            model_name='others',
            name='series_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='others',
            name='songs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Песня, в которой этот исполнитель учавствует'),
        ),
        migrations.AlterField(
            model_name='others',
            name='when_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='others',
            name='who_issued',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан'),
        ),
    ]
