# Generated by Django 3.2.5 on 2021-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20211021_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfodocs',
            name='content_type',
            field=models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=9, verbose_name='Тип релиза'),
        ),
    ]
