# Generated by Django 3.2.5 on 2021-10-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_maininfodocs_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfodocs',
            name='content_type',
        ),
    ]
