# Generated by Django 3.2.5 on 2021-10-28 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0014_remove_maininfodocs_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('passport', models.CharField(max_length=2024, verbose_name='Паспортные данные')),
                ('birth_place', models.CharField(max_length=2024, verbose_name='Место рождения')),
                ('reg', models.CharField(max_length=2024, verbose_name='Регистрация')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Электронная почта автора музыки')),
                ('fin_conditions', models.CharField(max_length=2024, verbose_name='Финансовые условия с автором музыки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhonMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('passport', models.CharField(max_length=2024, verbose_name='Паспортные данные')),
                ('birth_place', models.CharField(max_length=2024, verbose_name='Место рождения')),
                ('reg', models.CharField(max_length=2024, verbose_name='Регистрация')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Электронная почта изготовителя фонограммы')),
                ('fin_conditions', models.CharField(max_length=2024, verbose_name='Финансовые условия с изготовителем фонограммы')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('passport', models.CharField(max_length=2024, verbose_name='Паспортные данные')),
                ('birth_place', models.CharField(max_length=2024, verbose_name='Место рождения')),
                ('reg', models.CharField(max_length=2024, verbose_name='Регистрация')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Электронная почта автора слов')),
                ('fin_conditions', models.CharField(max_length=2024, verbose_name='Финансовые условия с автором слов')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='musicforeign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonmakercitizen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonmakerforeign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordscitizen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordsforeign',
            name='user',
        ),
        migrations.DeleteModel(
            name='MusicCitizen',
        ),
        migrations.DeleteModel(
            name='MusicForeign',
        ),
        migrations.DeleteModel(
            name='PhonMakerCitizen',
        ),
        migrations.DeleteModel(
            name='PhonMakerForeign',
        ),
        migrations.DeleteModel(
            name='WordsCitizen',
        ),
        migrations.DeleteModel(
            name='WordsForeign',
        ),
    ]
