# Generated by Django 3.2.5 on 2021-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20211028_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others',
            name='code_pod',
        ),
        migrations.RemoveField(
            model_name='others',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='others',
            name='series_num',
        ),
        migrations.RemoveField(
            model_name='others',
            name='when_issued',
        ),
        migrations.RemoveField(
            model_name='others',
            name='who_issued',
        ),
        migrations.AddField(
            model_name='others',
            name='passport',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='others',
            name='fin_conditions',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Финансовые условия с соисполнителем'),
        ),
    ]
