# Generated by Django 3.2.5 on 2021-10-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20211028_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicauthor',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
