# Generated by Django 3.2.5 on 2021-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_musicauthor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phonmaker',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wordsauthor',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
