# Generated by Django 3.2.5 on 2021-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20211029_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfodocs',
            name='release_type',
            field=models.CharField(choices=[('CLIP', 'Видеоклип'), ('SINGLE', 'Сингл'), ('ALBUM', 'Альбом / ЕР')], max_length=15, null=True, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='others',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта изготовителя фонограммы'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='birth_place',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='citizen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='fin_conditions',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Финансовые условия с изготовителем фонограммы'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='passport',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='phonmaker',
            name='reg',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Регистрация'),
        ),
    ]
