# Generated by Django 3.2.5 on 2021-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_maininfodocs_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfodocs',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Обложка (jpg 3000x3000)'),
        ),
        migrations.AlterField(
            model_name='maininfodocs',
            name='release_type',
            field=models.CharField(choices=[('CLIP', 'Видеоклип'), ('SINGLE', 'Сингл'), ('ALBUM', 'Альбом / ЕР')], default='SINGLE', max_length=15, null=True, verbose_name='Тип релиза'),
        ),
    ]
