# Generated by Django 3.2.5 on 2021-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_alter_maininfodocs_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfoipin',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='orginfoiprf',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='orginfoooo',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='orginfosam',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='Наименование банка'),
        ),
    ]
