# Generated by Django 3.2.5 on 2021-11-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_auto_20211118_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginfosam',
            name='birth_place',
        ),
    ]
