# Generated by Django 3.2.5 on 2021-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_remove_orginfosam_birth_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginfosam',
            name='skan_passport',
        ),
        migrations.AlterField(
            model_name='maininfodocs',
            name='release_type',
            field=models.CharField(choices=[('CLIP', 'Видеоклип'), ('SINGLE', 'Сингл'), ('ALBUM', 'Альбом / ЕР')], default='SINGLE', max_length=15, null=True, verbose_name='Тип релиза'),
        ),
    ]
