# Generated by Django 3.2.5 on 2021-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_auto_20211118_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicauthor',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='others',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='phonmaker',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='wordsauthor',
            name='birth_place',
        ),
        migrations.AlterField(
            model_name='maininfodocs',
            name='release_type',
            field=models.CharField(choices=[('CLIP', 'Видеоклип'), ('ALBUM', 'Альбом / ЕР'), ('SINGLE', 'Сингл')], default='SINGLE', max_length=15, null=True, verbose_name='Тип релиза'),
        ),
    ]
