# Generated by Django 3.2.5 on 2021-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0043_auto_20211118_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicauthor',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='others',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='phonmaker',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='wordsauthor',
            name='passport',
        ),
        migrations.AddField(
            model_name='musicauthor',
            name='code_pod',
            field=models.CharField(max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='musicauthor',
            name='series_num',
            field=models.CharField(max_length=100, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='musicauthor',
            name='when_issued',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='musicauthor',
            name='who_issued',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='others',
            name='code_pod',
            field=models.CharField(max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='others',
            name='series_num',
            field=models.CharField(max_length=100, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='others',
            name='when_issued',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='others',
            name='who_issued',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='phonmaker',
            name='code_pod',
            field=models.CharField(max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='phonmaker',
            name='series_num',
            field=models.CharField(max_length=100, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='phonmaker',
            name='when_issued',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='phonmaker',
            name='who_issued',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='wordsauthor',
            name='code_pod',
            field=models.CharField(max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='wordsauthor',
            name='series_num',
            field=models.CharField(max_length=100, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='wordsauthor',
            name='when_issued',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='wordsauthor',
            name='who_issued',
            field=models.CharField(max_length=500, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='maininfodocs',
            name='release_type',
            field=models.CharField(choices=[('SINGLE', 'Сингл'), ('ALBUM', 'Альбом / ЕР'), ('CLIP', 'Видеоклип')], default='SINGLE', max_length=15, null=True, verbose_name='Тип релиза'),
        ),
        migrations.AlterField(
            model_name='musicauthor',
            name='reg',
            field=models.CharField(max_length=2024, null=True, verbose_name='Регистрация'),
        ),
    ]
