# Generated by Django 3.2.5 on 2021-11-22 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя артиста')),
                ('fio', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('series_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия и номер паспорта')),
                ('who_issued', models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан')),
                ('when_issued', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('code_pod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подразделения')),
                ('reg', models.CharField(blank=True, max_length=2024, null=True, verbose_name='Адрес регистрации')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='VK')),
                ('inst', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('youtube', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube')),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True, verbose_name='TikTok')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
