# Generated by Django 3.2.5 on 2021-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lk',
            name='citizen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство'),
        ),
    ]
