# Generated by Django 3.2.5 on 2021-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_auto_20211118_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lk',
            name='code_pod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='lk',
            name='reg',
            field=models.CharField(blank=True, max_length=2024, null=True, verbose_name='Регистрация'),
        ),
        migrations.AlterField(
            model_name='lk',
            name='series_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='lk',
            name='when_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='lk',
            name='who_issued',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Кем выдан'),
        ),
    ]
